name: AI Code Review

on:
  pull_request:
    branches:
      - master
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  ai_review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || (github.event_name == 'issue_comment' && github.event.issue.pull_request)
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Python and dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install openai==0.28 pygithub

      - name: Run AI Code Review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
          EVENT_NAME: ${{ github.event_name }}
          COMMENT_ID: ${{ github.event.comment.id }}
        run: |
          echo "AI 코드 리뷰 실행 중..."
          python3 .github/workflows/ai_review.py